#!/bin/bash

#rm iris/*
#rm cancer/*

for i in {1..2}; do
	for y in {1..10}; do
		echo "cat iris-data.txt | ./split.bash 10 ./kmeans.py $y $i >> iris_n_${i}.txt;"
	done
done;

# for i in {1..140}; do
# 	for y in {1..100}; do
# 		echo "cat cancer-data.txt | ./split.bash 10 python kmeans.py $y $i >> cancer/cancer_n_${i}.txt;"
# 	done | parallel -j 4
# done;

# ./compile
